services:
  - type: web
    name: vortex-youtube-downloader
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: YOUTUBE_API_KEY
        sync: false
      - key: PORT
        value: 10000
